### ISSUE TITLE
使用 entrypoint 方式配置部屬會失敗

### ISSUE THREAD

**Issue by shiuh67** [RxChi1d/immich-geodata-zh-tw#3]
我使用QNAP Docker直接部屬 
entrypoint: [ "tini", "--", "/bin/bash", "-c", "bash <(curl -sSL https://raw.githubusercontent.com/RxChi1d/immich-geodata-zh-tw/refs/heads/main/update_data.sh) --install && exec /bin/bash start.sh" ]
這種方式啟動Docker ,會發生錯誤

tar: ./geodata: Cannot change mode to rwxr-xr-x: Bad address
tar: ./i18n-iso-countries/langs: Cannot change mode to rwxr-xr-x: Bad address
tar: ./i18n-iso-countries: Cannot change mode to rwxr-xr-x: Bad address
tar: Exiting with failure status due to previous errors

所以我只能用早期掛載外部資料夾的方式進行更新
無法隨著Docker啟動而更新資料

**Comment by shiuh67** [comment]
隨著測試發現載入後啟動會一直重複開啟程式的主要因素是解壓縮權限不夠，導致一直重複
只需要加入忽略警告就可以

將

# 解壓縮檔案
echo "開始解壓縮 release.tar.gz..."
tar -xvf "$DOWNLOAD_DIR/release.tar.gz" -C "$DOWNLOAD_DIR"

修改成

# 解壓縮檔案
echo "開始解壓縮 release.tar.gz..."
tar -xvf "$DOWNLOAD_DIR/release.tar.gz" -C "$DOWNLOAD_DIR" --no-same-permissions || echo "解壓縮過程中出現權限警告，但將繼續執行..."

我這邊就能正常執行
請您這邊參考看看，我的沒有加上這一行就不能使用您的方法更新

**Comment by RxChi1d** [comment]
目前我使用 portainer 重新部署了最新版本 (1.131.3)，似乎沒有遇到這個問題（內部使用者為 root）。

是否能請您提供您的 immich 版本並檢查 container 內部預設的使用者為何？

下面這是我部署時使用的 compose file：
```yaml
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    entrypoint: [ "tini", "--", "/bin/bash", "-c", "bash <(curl -sSL https://raw.githubusercontent.com/RxChi1d/immich-geodata-zh-tw/refs/heads/main/update_data.sh) --install && exec /bin/bash start.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
```

![Image](https://github.com/user-attachments/assets/fc2c5bc6-51d9-45be-8ad7-3ba87e185ace)

![Image](https://github.com/user-attachments/assets/d0c08dfb-becf-40dc-b164-5b6e5ec4538d)
